### ISSUE TITLE
firmwareUpdate dataformat components not working

### ISSUE THREAD

**Issue by MCLiii** [badgerloop-software/chase-car-dashboard#80]
Some big changes were made to the engineering dashboard, a lot of the components on Engineering dashboard are now bugging out due to missing fields/different field name.

## How to recreate the issue
Change the dataformat to firmwareUpdate branch by first going into the dataformat directory using `cd Backend/Data/sc1-data-format`, the run `git switch firmwareUpdate`, now run the chase-car-dashboard by `npm run start-dev`, and you should be bombarded by errors once the program starts.

### How to bypass the faltsview error
The faultsview error will prevent you from viewing anything on engineering dashboard, you can bypass the errors removing faults view from the display by going into `/Frontend/src/Components/Faults/FaultsView.js` and select everything from the last return statement in the code and replace with `return null`, please don't commit this though!!

**Comment by MCLiii** [comment]
A more detailed list of components that needs fixing

- [x] FaultsView #77 #81 
- [x] BatteryPack #82 
- [x] PPC_MPPT #84 
- [x] System_Power
- [x] Motor_Motion
- [x] Temperature

**Comment by MCLiii** [comment]
I am working on fixing faultsview
PR is up #81

**Comment by Rishit-5** [comment]
I am working on fixing Motor_Motion

**Comment by TheLawrus** [comment]
Working on Temperature
PR is up #83

**Comment by TheLawrus** [comment]
Working on System Power
PR is up #85
